on:
  webhook:
jobs:
  run:
    name: Verify
    runs-on: ubuntu-latest
    env:
      PROD_WEAVR_ADDRESS: "0x43240c0f5dedb375afd28206e02110e8fed8cFc0"
      DEV_WEAVR_ADDRESS: "0xFb3f5745dfD05bA3184156fcbd39D510136B0922"
      PROD_PROVIDER: "https://arbitrum-mainnet.infura.io/v3/10f965a85be14e40b1b7bb000a7be036"
      DEV_PROVIDER: "https://arbitrum-goerli.infura.io/v3/10f965a85be14e40b1b7bb000a7be036"
      BODY: ${{ toJson(on.webhook.outputs.body) }}
      PROD_PRIVATE_KEY: ${{ secrets.PROD_PRIVATE_KEY }}
      DEV_PRIVATE_KEY: ${{ secrets.DEV_PRIVATE_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: install deps
        run: npm install ethers@5.7.2
      - name: Record
        run:
          node $GITHUB_WORKSPACE/verification.js